// <auto-generated />
namespace a2.Migrations.SamaritanMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SecondCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201503051821431_SecondCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
